services:
  - type: web
    name: school-app-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: school-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: USE_MOCK_DB
        value: "false"
      - key: FALLBACK_TO_MOCK
        value: "false"

databases:
  - name: school-db
    databaseName: school_db
    plan: free
